@host = http://localhost:5171

GET {{host}}/weatherforecast/
Accept: application/json

POST {{host}}/companies
Content-Type: application/json

{
  "companyCode": "COMP001",
  "companyName": "Dream Dress Rentals Boutique",
  "isActive": true
}